# Your credentials
AWS_ACCESS_KEY = 'YOUR_AWS_ACCESS_KEY'
AWS_SECRET_KEY = 'YOUR_AWS_SECRET_KEY'
    
# Client-provided information
S3_BUCKET = 'YOUR_S3_BUCKET'
ROLE_ARN_TO_ASSUME = 'YOUR_ROLE_ARN_TO_ASSUME'
EXTERNAL_ID = 'YOUR_EXTERNAL_ID'

# Azure Creds
AZURE_CONNECTION_STRING = "YOUR_AZURE_CONNECTION_STRING"
AZURE_CONTAINER_NAME = "YOUR_AZURE_CONTAINER_NAME"